windowrule {
  name = fullscreen
  match:fullscreen = true
  no_dim = on
  border_color = rgb(f6955b)
}

windowrule {
  name = signal
  match:class = org.signal.Signal
  float = on
  persistent_size = on
}

windowrule {
  name = obs
  match:class = com.obsproject.Studio
  float = on
  persistent_size = on
}

windowrule {
  name = smile
  match:class = it.mijorus.smile
  float = on
}

windowrule {
  name = wl-clipboard
  match:title = wl-clipboard
  float = on
}

windowrule {
  name = filepicker
  match:class = xdg-desktop-portal-gtk
  float = on
}

windowrule {
  name = gimp
  match:class = (file-)(.*)
  match:title = (Export Image as )(.*)
  float = on
}

windowrule {
  name = calculator
  match:class = org.gnome.Calculator
  float = on
}

windowrule {
  name = mission-center
  match:class = io.missioncenter.MissionCenter
  float = on
  persistent_size = on
}